/**
 * Admin-facing notification email when a consultation call is booked.
 */
export function adminBookCallEmail({ name, email, company, scope, details, selectedDate, selectedTime, meetLink, source }) {
  return `
    <div style="font-family: sans-serif; color: #334155; line-height: 1.6; max-width: 600px; margin: auto; border: 1px solid #e2e8f0; padding: 25px; border-radius: 12px;">
      <h2 style="color: #0f172a; border-bottom: 2px solid #e2e8f0; padding-bottom: 12px; margin-top: 0;">New Consultation Call Booked!</h2>
      <p>A client has scheduled a 1-on-1 AI Strategy Session from the <strong>${source || 'Website'}</strong>.</p>
      
      <h3 style="color: #0284c7; border-bottom: 1px solid #f1f5f9; padding-bottom: 5px;">🗓️ Meeting Schedule</h3>
      <table style="width: 100%; border-collapse: collapse; margin-bottom: 20px; font-size: 14px;">
        <tr>
          <td style="padding: 6px 0; font-weight: bold; width: 30%;">Date/Day:</td>
          <td style="padding: 6px 0; color: #FF5500; font-weight: bold;">${selectedDate}</td>
        </tr>
        <tr>
          <td style="padding: 6px 0; font-weight: bold;">Time slot:</td>
          <td style="padding: 6px 0; color: #FF5500; font-weight: bold;">${selectedTime}</td>
        </tr>
        ${scope ? `<tr><td style="padding: 6px 0; font-weight: bold;">Objective:</td><td style="padding: 6px 0; color: #FF5500; font-weight: bold;">${scope}</td></tr>` : ''}
        <tr>
          <td style="padding: 6px 0; font-weight: bold; width: 30%;">Meet Link:</td>
          <td style="padding: 6px 0;"><a href="${meetLink}">${meetLink}</a></td>
        </tr>
      </table>

      <h3 style="color: #0284c7; border-bottom: 1px solid #f1f5f9; padding-bottom: 5px;">Client Profile</h3>
      <table style="width: 100%; border-collapse: collapse; margin-bottom: 20px; font-size: 14px;">
        <tr>
          <td style="padding: 6px 0; font-weight: bold; width: 30%;">Lead Name:</td>
          <td style="padding: 6px 0;">${name || 'Anonymous'}</td>
        </tr>
        <tr>
          <td style="padding: 6px 0; font-weight: bold;">Work Email:</td>
          <td style="padding: 6px 0;"><a href="mailto:${email}">${email}</a></td>
        </tr>
        <tr>
          <td style="padding: 6px 0; font-weight: bold;">Company Name:</td>
          <td style="padding: 6px 0;">${company || 'N/A'}</td>
        </tr>
        ${details ? `<tr><td style="padding: 6px 0; font-weight: bold;">Project Details:</td><td style="padding: 6px 0;">${details}</td></tr>` : ''}
      </table>
      
      <br/>
      <p style="font-size: 12px; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 10px; margin-bottom: 0;">
        This email was automatically generated by the AIMLpartner Call Booking Engine.
      </p>
    </div>
  `;
}
