/**
 * Admin-facing "Let's Build It!" notification email with client requirements and system prompt.
 */
export function adminBuildEmail({ name, email, company, departmentName, answers, analysisResult, selectedDate, selectedTime, meetLink, systemPromptText }) {
  return `
    <div style="font-family: sans-serif; color: #334155; line-height: 1.6; max-width: 650px; margin: auto; border: 1px solid #e2e8f0; padding: 25px; border-radius: 12px; box-shadow: 0 4px 6px -1px rgb(0 0 0 / 0.05);">
      <h2 style="color: #0f172a; border-bottom: 2px solid #e2e8f0; padding-bottom: 12px; margin-top: 0;">Let's Build It! Custom Agent Request & Demo Booked</h2>
      <p>A client has completed the Playbook Questionnaire and scheduled a live prototype walk-through for a custom AI Agent in their <strong>${departmentName}</strong> department.</p>
      
      <h3 style="color: #0284c7; border-bottom: 1px solid #f1f5f9; padding-bottom: 5px;">🗓️ Live Demo Schedule</h3>
      <table style="width: 100%; border-collapse: collapse; margin-bottom: 20px; font-size: 14px;">
        <tr>
          <td style="padding: 6px 0; font-weight: bold; width: 30%;">Date/Day:</td>
          <td style="padding: 6px 0; color: #4338ca; font-weight: bold;">${selectedDate || 'Not specified'}</td>
        </tr>
        <tr>
          <td style="padding: 6px 0; font-weight: bold;">Time slot:</td>
          <td style="padding: 6px 0; color: #4338ca; font-weight: bold;">${selectedTime || 'Not specified'}</td>
        </tr>
        <tr>
          <td style="padding: 6px 0; font-weight: bold; width: 30%;">Meet Link:</td>
          <td style="padding: 6px 0;"><a href="${meetLink}">${meetLink}</a></td>
        </tr>
      </table>

      <h3 style="color: #0284c7; border-bottom: 1px solid #f1f5f9; padding-bottom: 5px;">Client Profile</h3>
      <table style="width: 100%; border-collapse: collapse; margin-bottom: 20px; font-size: 14px;">
        <tr>
          <td style="padding: 6px 0; font-weight: bold; width: 30%;">Lead Name:</td>
          <td style="padding: 6px 0;">${name}</td>
        </tr>
        <tr>
          <td style="padding: 6px 0; font-weight: bold;">Work Email:</td>
          <td style="padding: 6px 0;"><a href="mailto:${email}">${email}</a></td>
        </tr>
        <tr>
          <td style="padding: 6px 0; font-weight: bold;">Company Name:</td>
          <td style="padding: 6px 0;">${company}</td>
        </tr>
        <tr>
          <td style="padding: 6px 0; font-weight: bold;">Business Sector:</td>
          <td style="padding: 6px 0;">${analysisResult?.sector || 'Services'}</td>
        </tr>
      </table>

      <h3 style="color: #0284c7; border-bottom: 1px solid #f1f5f9; padding-bottom: 5px;">Custom Requirements Clarified</h3>
      <div style="background-color: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 15px; margin-bottom: 20px; font-size: 14px;">
        ${answers.map((a, i) => `
          <p style="margin: 0 0 8px 0;"><strong>Q${i + 1}: ${a.question}</strong></p>
          <p style="margin: 0 0 16px 0; color: #475569; font-style: italic;">A${i + 1}: ${a.answer}</p>
        `).join('')}
      </div>

      <h3 style="color: #4f46e5; border-bottom: 2px solid #e2e8f0; padding-bottom: 5px; margin-top: 30px;">Google AI Studio System Prompt Blueprint</h3>
      <p style="font-size: 13px; color: #64748b; margin-top: 5px; margin-bottom: 15px;">
        Copy and paste the generated system prompt block below directly into Google AI Studio system instructions to spin up this agent immediately!
      </p>
      <div style="background-color: #0f172a; color: #e2e8f0; font-family: monospace; font-size: 12px; padding: 15px; border-radius: 8px; overflow-x: auto; white-space: pre-wrap; border: 1px solid #1e293b; max-height: 500px;">
${systemPromptText}
      </div>
      
      <br/>
      <p style="font-size: 12px; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 10px; margin-bottom: 0;">
        This email was automatically generated by the AIMLpartner Custom Analyzer Engine. Follow up with the lead at ${email}.
      </p>
    </div>
  `;
}
